/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sis_viajes;

import javax.swing.ImageIcon;

/**
 *
 * @author lsfer
 */
public class Ayuda_Operadores extends javax.swing.JFrame {

    /**
     * Creates new form Ayuda_Operadores
     */
    public Ayuda_Operadores() {
        initComponents();
        taRespuesta.setText(""
      + "Para guardar el nombre de un operador: \r\n"
      + "Escriba en el campo de texto en blanco que está enseguida donde dice \"Empresa\" el nombre del operador que desea agrgear;"
      + " después, haga clic en el boton de Agregar, ubicado en la parte superior izquierda de la ventana, represntado con un ícono"
      + "de \"+\"");
        this.setTitle("Ayuda - Operadores");
        this.setIconImage(new ImageIcon(getClass().getResource("icono.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboPreguntas = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taRespuesta = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(180, 52, 29));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("¿En qué lo puedo ayudar?");

        comboPreguntas.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        comboPreguntas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cómo guardar el nombre de un operador", "Cómo editar el nombre de un operador", "Cómo buscar un operador", "Cómo listar todos los operadores que he registrado", "Cómo salir al menú principal", "Usar la tecla enter para agregar un operador" }));
        comboPreguntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPreguntasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboPreguntas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 529, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboPreguntas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(234, 177, 100));

        taRespuesta.setEditable(false);
        taRespuesta.setColumns(20);
        taRespuesta.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        taRespuesta.setLineWrap(true);
        taRespuesta.setRows(5);
        jScrollPane1.setViewportView(taRespuesta);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 783, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(19, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 92, -1, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboPreguntasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPreguntasActionPerformed
        switch(comboPreguntas.getSelectedIndex()) {
            case 0: {
                taRespuesta.setText(""
                + "Para guardar el nombre de un operador: \r\n"
                + "Escriba en el campo de texto en blanco que está enseguida donde dice \"Empresa\" el nombre del operador que desea agrgear;"
                + " después, haga clic en el boton de Agregar, ubicado en la parte superior izquierda de la ventana, represntado con un ícono"
                + " de \"+\"");
                break;
            }
            
            case 1: {
                taRespuesta.setText(""
                + "Para editar el nombre de un operador: \r\n"
                + "Si se equivocó al escribir el nombre de un operador, seleccione en la tabla el registro con el nombre del operador correspondiente al que desea modificarle"
                + " su nombre. Después, el programa pasará el nombre al campo de texto en blanco para que usted lo pueda editar. \r\n"
                + "Ahí puede editar el nombre, y cuando esté listo, haga clic en el botón ubicado en la parte superior izquierda,"
                + " representado por un icono de lápiz");
                break;
            }
            
            case 2: {
                taRespuesta.setText(""
                + "Para buscar un operador: \r\n"
                + "Escriba (una parte o completo) el nombre del operador que desea buscar en el campo de texto en blanco. \r\n"
                + "Después, haga clic en el botón ubicado en la parte superior izquierda representado por una lupa. \r\n"
                + "El programá se encargará de buscar coincidencias. Si las encuentra, se las listará en la tabla. Si no encuentra"
                + " coincidencias, la tabla estará vacía. \r\n"
                + "Si desea volver a listar todos los operadores, deje el campo de texto en blanco y luego haga clic el en botón "
                + "representado con una lupa.");
                break;
            }
            
            case 3: {
                taRespuesta.setText(""
                + "Para listar todos los operadores que ha registrado: \r\n"
                + "Asegúrese de dejar el campo de texto completamente en blanco. Después, haga clic en el botón ubicado en la parte"
                + " superior izquierda, representado por una lupa. El programa volverá a listar todo nuevamente.");
                break;
            }
            
            case 4: {
                taRespuesta.setText(""
                + "Para salir al menú principal: \r\n"
                + "Haga clic en el botón ubicado en la parte superior izquierda, representado por una flecha apuntado hacia la izquierda.");
                break;
            }
            
            case 5: {
                taRespuesta.setText(""
                + "Puede agregar un operador sin tener que mover el cursor hasta el botón de agregar. \r\n"
                + "Para ello: cuando termine de escribir el nombre del operador, en el mismo campo de texto presione la tecla enter y el programa guardará el registro.");
            }
        }
    }//GEN-LAST:event_comboPreguntasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ayuda_Operadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ayuda_Operadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ayuda_Operadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ayuda_Operadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ayuda_Operadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboPreguntas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taRespuesta;
    // End of variables declaration//GEN-END:variables
}
