/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sis_viajes;

import javax.swing.ImageIcon;

/**
 *
 * @author lsfer
 */
public class Ayuda_Clientes extends javax.swing.JFrame {

    /**
     * Creates new form Ayuda_Clientes
     */
    public Ayuda_Clientes() {
        initComponents();
        this.setTitle("Ayuda - Clientes");
        taRespuesta.setText(""
                    + "Para guardar los datos de un cliente: \r\n"
                    + "Llene los campos que sean necesarios de la información que le ha solicitado al cliente (LOS CAMPOS "
                        + "\"Apellido Paterno\" y \"Nombre\" SON OBLIGATORIOS). \r\n"
                        + "Después, haga clic en el botón de agregar, simbolizado con un ícono de \"+\". "
                        + "Si ubica el cursor del teclado en los campos: Nombre, Año de fecha de nacimiento o No. Club Premier, "
                        + "podrá presionar la tecla enter para agregar al cliente sin hacer clic al botón correspondiente");
        this.setIconImage(new ImageIcon(getClass().getResource("icono.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboPreguntas = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taRespuesta = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(180, 52, 29));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("¿En qué lo puedo ayudar?");

        comboPreguntas.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        comboPreguntas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cómo guardar los datos de un cliente", "Cómo editar los datos de un cliente", "Cómo buscar un cliente", "Cómo listar todos los clientes que he registrado", "Cómo salir al menú principal", "Usar la tecla enter para agregar un cliente" }));
        comboPreguntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPreguntasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboPreguntas, 0, 759, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboPreguntas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(234, 177, 100));

        taRespuesta.setEditable(false);
        taRespuesta.setColumns(20);
        taRespuesta.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        taRespuesta.setLineWrap(true);
        taRespuesta.setRows(5);
        jScrollPane1.setViewportView(taRespuesta);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 783, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(19, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 783, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(92, 92, 92)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboPreguntasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPreguntasActionPerformed
        switch(comboPreguntas.getSelectedIndex()) {
            case 0: {
                taRespuesta.setText(""
                    + "Para guardar los datos de un cliente: \r\n"
                    + "Llene los campos que sean necesarios de la información que le ha solicitado al cliente (LOS CAMPOS "
                        + "\"Apellido Paterno\" y \"Nombre\" SON OBLIGATORIOS). \r\n"
                        + "Después, haga clic en el botón de agregar, simbolizado con un ícono de \"+\". "
                        + "Si ubica el cursor del teclado en los campos: Nombre, Año de fecha de nacimiento o No. Club Premier, "
                        + "podrá presionar la tecla enter para agregar al cliente sin hacer clic al botón correspondiente");
                break;
            }

            case 1: {
                taRespuesta.setText(""
                    + "Para editar uno o varios datos de un cliente: \r\n"
                    + "Si se equivocó al escribir algún dato del cliente, seleccione en la tabla el registro con los datos de un cliente correspondiente al que desea modificarle"
                    + " sus datos. Después, el programa pasará todos los datos del cliente al formulario que se encuentra debajo para que usted los pueda editar. \r\n"
                    + "En ese formulario, podrá editar el campo que desee (con las mismas restricciones que al agregar), y cuando esté listo, haga clic en el botón ubicado en la parte superior izquierda,"
                    + " representado por un icono de lápiz");
                break;
            }

            case 2: {
                taRespuesta.setText(""
                    + "Para buscar un cliente: \r\n"
                    + "Escoga una característica por donde buscar al cliente, y después escriba (una parte o completo) el texto en el campo de texto en blanco. \r\n"
                    + "Después, haga clic en el botón ubicado en la parte superior izquierda representado por una lupa. \r\n"
                    + "El programá se encargará de buscar coincidencias. Si las encuentra, se las listará en la tabla. Si no encuentra"
                    + " coincidencias, la tabla estará vacía. \r\n"
                    + "Si desea volver a listar todos los clientes, deje el campo de texto en blanco y luego haga clic el en botón "
                    + "representado con una lupa.");
                break;
            }

            case 3: {
                taRespuesta.setText(""
                    + "Para listar todos los clientes que ha registrado: \r\n"
                    + "Asegúrese de dejar el campo de texto completamente en blanco. Después, haga clic en el botón ubicado en la parte"
                    + " superior izquierda, representado por una lupa. El programa volverá a listar todo nuevamente.");
                break;
            }

            case 4: {
                taRespuesta.setText(""
                    + "Para salir al menú principal: \r\n"
                    + "Haga clic en el botón ubicado en la parte superior izquierda, representado por una flecha apuntado hacia la izquierda.");
                break;
            }

            case 5: {
                taRespuesta.setText(""
                    + "Puede agregar un cliente sin tener que mover el cursor hasta el botón de agregar. \r\n"
                    + "Para ello: ubique el cursor del teclado (o haga clic) en los campos nombre, fecha de nacimieno (en el año) o en No. Club Premier y depués presione la tecla enter para que el programa guarde el registro.");
            }
        }
    }//GEN-LAST:event_comboPreguntasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ayuda_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ayuda_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ayuda_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ayuda_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ayuda_Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboPreguntas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taRespuesta;
    // End of variables declaration//GEN-END:variables
}
