/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sis_viajes;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author lsfer
 */
public class Menu_Principal extends javax.swing.JFrame {
    
    static boolean necesita_ayudas = false;
    /**
     * Creates new form Menu_Principal
     */
    public Menu_Principal() {
        initComponents();
        this.setTitle("Menú Principal");
        this.setIconImage(new ImageIcon(getClass().getResource("icono.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bClientes = new javax.swing.JButton();
        bReservaciones = new javax.swing.JButton();
        bReservaciones1 = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        checkAyudas = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(445, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bClientes.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        bClientes.setText("Clientes");
        bClientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClientesActionPerformed(evt);
            }
        });
        getContentPane().add(bClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 225, 175, 73));

        bReservaciones.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        bReservaciones.setText("Reservaciones");
        bReservaciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bReservaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReservacionesActionPerformed(evt);
            }
        });
        getContentPane().add(bReservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 225, 175, 73));

        bReservaciones1.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        bReservaciones1.setText("Operadores");
        bReservaciones1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bReservaciones1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReservaciones1ActionPerformed(evt);
            }
        });
        getContentPane().add(bReservaciones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 309, 175, 73));

        bSalir.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        bSalir.setText("Salir");
        bSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });
        getContentPane().add(bSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 309, 175, 73));

        checkAyudas.setBackground(new java.awt.Color(234, 177, 100));
        checkAyudas.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 11)); // NOI18N
        checkAyudas.setText("Activar ayudas");
        checkAyudas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAyudasActionPerformed(evt);
            }
        });
        getContentPane().add(checkAyudas, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 400, -1, -1));

        jPanel1.setBackground(new java.awt.Color(234, 177, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sis_viajes/principal.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(257, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClientesActionPerformed
        Mod_Clientes modulo_clientes = new Mod_Clientes();
        modulo_clientes.setVisible(true);
        modulo_clientes.setLocationRelativeTo(null);
        modulo_clientes.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       
    }//GEN-LAST:event_bClientesActionPerformed

    private void bReservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReservacionesActionPerformed
        Mod_Reservaciones modulo_reservaciones = new Mod_Reservaciones();
        modulo_reservaciones.setVisible(true);
        modulo_reservaciones.setLocationRelativeTo(null);
        modulo_reservaciones.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_bReservacionesActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_bSalirActionPerformed

    private void bReservaciones1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReservaciones1ActionPerformed
        Mod_Operadores modulo_operadores = new Mod_Operadores();
        modulo_operadores.setVisible(true);
        modulo_operadores.setLocationRelativeTo(null);
        modulo_operadores.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_bReservaciones1ActionPerformed

    private void checkAyudasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAyudasActionPerformed
        if(checkAyudas.isSelected()){
            necesita_ayudas = true;
        } else {
            necesita_ayudas = false;
        }
    }//GEN-LAST:event_checkAyudasActionPerformed

    private static boolean requiere_ayudas(){
        return necesita_ayudas;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClientes;
    private javax.swing.JButton bReservaciones;
    private javax.swing.JButton bReservaciones1;
    private javax.swing.JButton bSalir;
    private javax.swing.JCheckBox checkAyudas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
