/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sis_viajes;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author lsfer
 */
public class Mod_Clientes extends javax.swing.JFrame {

    /**
     * Creates new form Mod_Clientes
     */
    public Mod_Clientes() {
        initComponents();
        actualizarTabla();
        this.establecerLabelNoVisible();
        if(Menu_Principal.necesita_ayudas){
            lAyudaClientes.setVisible(true);
            lAyudaClientes.setText("Consejo: ubique el cursor en los campos -Nombre-, -Año- o -No. Club Premier- y presione la tecla ENTER para agregar un cliente");
        } else {
            lAyudaClientes.setVisible(false);
        } 
        
        this.setTitle("Módulo Clientes");
        this.setIconImage(new ImageIcon(getClass().getResource("icono.png")).getImage());
    }
    
    private String id_cliente_actual = "";
    private int[] id_clientes;
    private int cantidad_id=0;
    private int tamaño_Columnas=98;
    
    private void actualizarTabla() {
        try {
            cantidad_id = 0;
            
            DefaultTableModel modelo = new CustomTableModel();
            jTClientes.setModel(modelo);
            
            
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion connection = new Conexion();
            Connection con = connection.getConexion();
            
            String sql = "SELECT Apellido_Paterno, Apellido_Materno, Nombre, Compañia, Fecha_Nacimiento, Sexo, No_Club_Premier FROM clientes";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();
            modelo.addColumn("Apellido Paterno");
            modelo.addColumn("Apellido Materno");
            modelo.addColumn("Nombre");
            modelo.addColumn("Compañia");
            modelo.addColumn("Fecha Nacimiento");
            modelo.addColumn("Sexo");
            modelo.addColumn("No. Club Premier");
            
            for (int i=0; i <= 6; i++) {
              jTClientes.getColumnModel().getColumn(i).setPreferredWidth(tamaño_Columnas);  
            }
             
            while(rs.next()) {
                Object[] filas = new Object[cantidadColumnas]; //ya que la tabla trabaja con objetos, metemos todo en objetos
                
                for (int i=0; i < cantidadColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                
                cantidad_id++;
                modelo.addRow(filas);
            }
            
            con.close();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error:" + e);
        }
        
        id_clientes = new int[cantidad_id];
        
        this.listarID();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        bSalir = new javax.swing.JButton();
        bAgregar = new javax.swing.JButton();
        bEditar = new javax.swing.JButton();
        bBuscar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pRegistro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bBorrar = new javax.swing.JButton();
        tCompania = new javax.swing.JTextField();
        tApPaterno = new javax.swing.JTextField();
        tApMaterno = new javax.swing.JTextField();
        tNombre = new javax.swing.JTextField();
        tDia = new javax.swing.JTextField();
        tSexo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tMes = new javax.swing.JTextField();
        tAnio = new javax.swing.JTextField();
        tNoClubPremier = new javax.swing.JTextField();
        labelAño = new javax.swing.JLabel();
        labelDia = new javax.swing.JLabel();
        labelMes = new javax.swing.JLabel();
        pConsultas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTClientes = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        comboEntidadesClientes = new javax.swing.JComboBox<>();
        tBuscar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tNoClubPremierMod = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tSexoMod = new javax.swing.JComboBox<>();
        tDiaMod = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tMesMod = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tAnioMod = new javax.swing.JTextField();
        tCompañiaMod = new javax.swing.JTextField();
        tApPaternoMod = new javax.swing.JTextField();
        tApMaternoMod = new javax.swing.JTextField();
        tNombreMod = new javax.swing.JTextField();
        labelDiaMod = new javax.swing.JLabel();
        labelMesMod = new javax.swing.JLabel();
        labelAñoMod = new javax.swing.JLabel();
        bBorrarMod = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lAyudaClientes = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(751, 612));
        setPreferredSize(new java.awt.Dimension(766, 699));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setBackground(new java.awt.Color(180, 52, 29));
        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        bSalir.setBackground(new java.awt.Color(234, 177, 100));
        bSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sis_viajes/ico_salir.png"))); // NOI18N
        bSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bSalir.setFocusable(false);
        bSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bSalirMouseExited(evt);
            }
        });
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });
        jToolBar1.add(bSalir);

        bAgregar.setBackground(new java.awt.Color(234, 177, 100));
        bAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sis_viajes/ico_agregar.png"))); // NOI18N
        bAgregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bAgregar.setFocusable(false);
        bAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bAgregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bAgregarMouseExited(evt);
            }
        });
        bAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarActionPerformed(evt);
            }
        });
        jToolBar1.add(bAgregar);

        bEditar.setBackground(new java.awt.Color(234, 177, 100));
        bEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sis_viajes/ico_editar.png"))); // NOI18N
        bEditar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bEditar.setEnabled(false);
        bEditar.setFocusable(false);
        bEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bEditarMouseExited(evt);
            }
        });
        bEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditarActionPerformed(evt);
            }
        });
        jToolBar1.add(bEditar);

        bBuscar.setBackground(new java.awt.Color(234, 177, 100));
        bBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sis_viajes/ico_buscar.png"))); // NOI18N
        bBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bBuscar.setEnabled(false);
        bBuscar.setFocusable(false);
        bBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bBuscarMouseExited(evt);
            }
        });
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });
        jToolBar1.add(bBuscar);

        jButton1.setBackground(new java.awt.Color(234, 177, 100));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sis_viajes/ico_ayuda.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setMinimumSize(new java.awt.Dimension(15, 15));
        jButton1.setPreferredSize(new java.awt.Dimension(31, 31));
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, -1));

        jTabbedPane1.setBackground(new java.awt.Color(234, 177, 100));
        jTabbedPane1.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 12)); // NOI18N
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(712, 565));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        pRegistro.setBackground(new java.awt.Color(234, 177, 100));
        pRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 24)); // NOI18N
        jLabel1.setText("Empresa:");
        pRegistro.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 24)); // NOI18N
        jLabel2.setText("Apellido Paterno:");
        pRegistro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 24)); // NOI18N
        jLabel3.setText("Apellido Materno:");
        pRegistro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 24)); // NOI18N
        jLabel4.setText("Nombre(s):");
        pRegistro.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 24)); // NOI18N
        jLabel5.setText("Fecha Nacimiento:");
        pRegistro.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jLabel6.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 24)); // NOI18N
        jLabel6.setText("No. Club Premier:");
        pRegistro.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        jLabel7.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 24)); // NOI18N
        jLabel7.setText("Sexo:");
        pRegistro.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, -1, -1));

        bBorrar.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 14)); // NOI18N
        bBorrar.setText("Limpiar");
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarActionPerformed(evt);
            }
        });
        pRegistro.add(bBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, -1));

        tCompania.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 24)); // NOI18N
        tCompania.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tCompaniaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tCompaniaFocusLost(evt);
            }
        });
        pRegistro.add(tCompania, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 463, -1));

        tApPaterno.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 24)); // NOI18N
        tApPaterno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tApPaternoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tApPaternoFocusLost(evt);
            }
        });
        pRegistro.add(tApPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 463, -1));

        tApMaterno.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 24)); // NOI18N
        tApMaterno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tApMaternoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tApMaternoFocusLost(evt);
            }
        });
        pRegistro.add(tApMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 464, -1));

        tNombre.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 24)); // NOI18N
        tNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tNombreFocusLost(evt);
            }
        });
        tNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tNombreKeyPressed(evt);
            }
        });
        pRegistro.add(tNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 464, -1));

        tDia.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 24)); // NOI18N
        tDia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tDiaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tDiaFocusLost(evt);
            }
        });
        pRegistro.add(tDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 59, -1));

        tSexo.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 24)); // NOI18N
        tSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));
        pRegistro.add(tSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 51, 40));

        jLabel8.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 24)); // NOI18N
        jLabel8.setText("/");
        pRegistro.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, -1, -1));

        jLabel9.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 24)); // NOI18N
        jLabel9.setText("/");
        pRegistro.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, -1, -1));

        tMes.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 24)); // NOI18N
        tMes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tMesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tMesFocusLost(evt);
            }
        });
        pRegistro.add(tMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 59, -1));

        tAnio.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 24)); // NOI18N
        tAnio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tAnioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tAnioFocusLost(evt);
            }
        });
        tAnio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tAnioKeyPressed(evt);
            }
        });
        pRegistro.add(tAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 150, 40));

        tNoClubPremier.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 24)); // NOI18N
        tNoClubPremier.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tNoClubPremierFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tNoClubPremierFocusLost(evt);
            }
        });
        tNoClubPremier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tNoClubPremierKeyPressed(evt);
            }
        });
        pRegistro.add(tNoClubPremier, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 464, -1));

        labelAño.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 12)); // NOI18N
        labelAño.setText("AAAA");
        pRegistro.add(labelAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, -1, -1));

        labelDia.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 12)); // NOI18N
        labelDia.setText("DD");
        pRegistro.add(labelDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, -1, -1));

        labelMes.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 12)); // NOI18N
        labelMes.setText("MM");
        pRegistro.add(labelMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, -1, -1));

        jTabbedPane1.addTab("Registro", pRegistro);

        pConsultas.setBackground(new java.awt.Color(234, 177, 100));
        pConsultas.setPreferredSize(new java.awt.Dimension(776, 555));
        pConsultas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTClientes.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 12)); // NOI18N
        jTClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Apellido Paterno", "Apellido Materno", "Nombre", "Compañia", "Fecha Nacimiento", "Sexo", "No. Club Premier"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTClientes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTClientes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTClientesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTClientesFocusLost(evt);
            }
        });
        jTClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTClientesMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(jTClientes);

        pConsultas.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 81, 704, 138));

        jLabel12.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        jLabel12.setText("Buscar por:");
        pConsultas.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 28, -1, -1));

        comboEntidadesClientes.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        comboEntidadesClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Compañia", "Apellido Paterno", "Apellido Materno", "Nombre" }));
        pConsultas.add(comboEntidadesClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 25, 204, -1));

        tBuscar.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        tBuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tBuscarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tBuscarFocusLost(evt);
            }
        });
        pConsultas.add(tBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 25, 385, -1));

        jLabel10.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        jLabel10.setText("Compañia:");
        pConsultas.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 280, -1, -1));

        jLabel11.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        jLabel11.setText("MODIFICAR DATOS");
        pConsultas.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel13.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        jLabel13.setText("Apellido Paterno:");
        pConsultas.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 322, -1, -1));

        jLabel14.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        jLabel14.setText("Apellido Materno:");
        pConsultas.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 366, -1, -1));

        jLabel15.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        jLabel15.setText("Nombre(s):");
        pConsultas.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 408, -1, -1));

        jLabel16.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        jLabel16.setText("Fecha Nacimiento:");
        pConsultas.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 450, -1, -1));

        jLabel17.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        jLabel17.setText("No. Club Premier:");
        pConsultas.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 515, -1, -1));

        tNoClubPremierMod.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        tNoClubPremierMod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tNoClubPremierModKeyPressed(evt);
            }
        });
        pConsultas.add(tNoClubPremierMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 512, 492, -1));

        jLabel18.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        jLabel18.setText("Sexo:");
        pConsultas.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, -1, -1));

        tSexoMod.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        tSexoMod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));
        pConsultas.add(tSexoMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 447, 65, -1));

        tDiaMod.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        tDiaMod.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tDiaModFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tDiaModFocusLost(evt);
            }
        });
        pConsultas.add(tDiaMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 447, 68, -1));

        jLabel19.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        jLabel19.setText("/");
        pConsultas.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 450, -1, -1));

        tMesMod.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        tMesMod.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tMesModFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tMesModFocusLost(evt);
            }
        });
        pConsultas.add(tMesMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 447, 57, -1));

        jLabel20.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        jLabel20.setText("/");
        pConsultas.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, -1, -1));

        tAnioMod.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        tAnioMod.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tAnioModFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tAnioModFocusLost(evt);
            }
        });
        tAnioMod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tAnioModKeyPressed(evt);
            }
        });
        pConsultas.add(tAnioMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 447, 147, -1));

        tCompañiaMod.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        tCompañiaMod.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tCompañiaModFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tCompañiaModFocusLost(evt);
            }
        });
        pConsultas.add(tCompañiaMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 277, 493, -1));

        tApPaternoMod.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        tApPaternoMod.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tApPaternoModFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tApPaternoModFocusLost(evt);
            }
        });
        pConsultas.add(tApPaternoMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 319, 493, -1));

        tApMaternoMod.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        tApMaternoMod.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tApMaternoModFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tApMaternoModFocusLost(evt);
            }
        });
        pConsultas.add(tApMaternoMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 363, 493, -1));

        tNombreMod.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        tNombreMod.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tNombreModFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tNombreModFocusLost(evt);
            }
        });
        tNombreMod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tNombreModKeyPressed(evt);
            }
        });
        pConsultas.add(tNombreMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 405, 493, -1));

        labelDiaMod.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 12)); // NOI18N
        labelDiaMod.setText("DD");
        pConsultas.add(labelDiaMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, -1, -1));

        labelMesMod.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 12)); // NOI18N
        labelMesMod.setText("MM");
        pConsultas.add(labelMesMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, -1, -1));

        labelAñoMod.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 12)); // NOI18N
        labelAñoMod.setText("AAAA");
        pConsultas.add(labelAñoMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, -1, -1));

        bBorrarMod.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 14)); // NOI18N
        bBorrarMod.setText("Limpiar");
        bBorrarMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarModActionPerformed(evt);
            }
        });
        pConsultas.add(bBorrarMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, -1, -1));

        jTabbedPane1.addTab("Consultas", pConsultas);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 46, 740, 580));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        lAyudaClientes.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 10)); // NOI18N
        jPanel2.add(lAyudaClientes);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 760, 30));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 760, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void establecerLabelNoVisible() {
        labelDia.setVisible(false);
        labelDiaMod.setVisible(false);
        labelMes.setVisible(false);
        labelMesMod.setVisible(false);
        labelAño.setVisible(false);
        labelAñoMod.setVisible(false);
    }
    
    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_bSalirActionPerformed
    
    private boolean ComprobarApPaterno() {
        boolean existe;
        if(tApPaterno.getText().trim().equals("")) {
            existe = false;
        } else {
            existe = true;
        } 
        return existe;
    }
    
    private boolean ComprobarNombre() {
        boolean existe;
        if(tNombre.getText().trim().equals("")) {
            existe = false;
        } else {
            existe = true;
        } 
        return existe;
    }
    
    private boolean RevisarFecha() {
        String fecha = tDia.getText().trim() + "/" + tMes.getText().trim() + "/" + tAnio.getText().trim();
        if(tDia.getText().trim().length()>0 && tMes.getText().trim().length()>0 && tAnio.getText().trim().length()>0) {
             try {
                SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
                formatoFecha.setLenient(false);
                formatoFecha.parse(fecha);
            } catch (ParseException e) {
                return false;
            }
             return true;
        } else {
            return true;
        }
    }
    
    private boolean RevisarDigitosFecha() {
        boolean esta_Bien;
        if(tDia.getText().length()==2 && tMes.getText().length()==2 && tAnio.getText().length()==4) {
            esta_Bien = true;
        } else {
            esta_Bien = false;
        } 
        return esta_Bien;
    }
    
    private void agregar() {
        boolean ap_Paterno_Existe = this.ComprobarApPaterno();
        boolean nombre_Existe = this.ComprobarNombre();
        boolean Digitos_Fecha_Bien = true;
        boolean Fecha_Bien = true;
        
        if (!(tDia.getText().trim().equals("") && tMes.getText().trim().equals("") && tAnio.getText().trim().equals(""))) {
           Digitos_Fecha_Bien = this.RevisarDigitosFecha();
           Fecha_Bien = this.RevisarFecha(); 
        }
        
        if(ap_Paterno_Existe && nombre_Existe && Digitos_Fecha_Bien && Fecha_Bien){
            if((tDia.getText().trim().equals("") && tMes.getText().trim().equals("") && tAnio.getText().trim().equals(""))
                || (tDia.getText().trim().length()>0 && tMes.getText().trim().length()>0 && tAnio.getText().trim().length()>0)) {
               
               String compañia = tCompania.getText(), 
               apellido_Paterno = tApPaterno.getText(), 
               apellido_Materno = tApMaterno.getText(), 
               nombre = tNombre.getText(), 
               dia = tDia.getText(), 
               mes = tMes.getText(), 
               año = tAnio.getText(), 
               fecha_nacimiento = dia + "/" + mes + "/" + año, 
               sexo = tSexo.getSelectedItem().toString();
           
            int no_Club_Premier;
            if(!tNoClubPremier.getText().equals("")) {
                no_Club_Premier = Integer.parseInt(tNoClubPremier.getText());
            } else {
                no_Club_Premier = 0;
            }
            
            if(tDia.getText().trim().equals("") && tMes.getText().trim().equals("") && tAnio.getText().trim().equals("")) {
               fecha_nacimiento = "";     
            }
            
            Altas operacion = new Altas();
            operacion.alta(compañia, apellido_Paterno, apellido_Materno, nombre, fecha_nacimiento, sexo, no_Club_Premier);
            borrarDatos();
            } else {
                JOptionPane.showMessageDialog(null, "Se detecto que en la fecha falta especificar un dato. Se debe especificar dia, mes y año en el siguiente formato: DD/MM/AAAA.","Operación fallida", JOptionPane.WARNING_MESSAGE);
            }    
        } else {
            
            if(!ap_Paterno_Existe) {
               JOptionPane.showMessageDialog(null, "El campo <Apellido Paterno> es obligatorio","Operación fallida", JOptionPane.WARNING_MESSAGE);
            }
            
            if(!nombre_Existe) {
               JOptionPane.showMessageDialog(null, "El campo <Nombre> es obligatorio","Operación fallida", JOptionPane.WARNING_MESSAGE); 
            }
            
            if(!Digitos_Fecha_Bien){
               JOptionPane.showMessageDialog(null, "El formato de la fecha no es correcto. El formato debe ser como sigue: DD/MM/AAAA (dos digitos para el dia, dos digitos para el mes, cuatro digitos para el año)","Operación fallida", JOptionPane.WARNING_MESSAGE);
            }
            
            if(!Fecha_Bien){
               JOptionPane.showMessageDialog(null, "La fecha no es correcta. Revise si: el dia no supere 30 o 31 dias dependiendo el mes, o bien 28 si es febrero y no es año bisiesto, o 29 si es año bisiesto; el mes debe estar entre 01 y 12; el año debe ser mayor a 0","Operación fallida", JOptionPane.WARNING_MESSAGE);
            }
        }   
    }
    
    private void bAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarActionPerformed
        this.agregar();
    }//GEN-LAST:event_bAgregarActionPerformed

    private void borrarDatos() {
        
        tApPaterno.setText("");
        tApMaterno.setText("");
        tNombre.setText("");
        tCompania.setText("");
        tDia.setText("");
        tMes.setText("");
        tAnio.setText("");
        tNoClubPremier.setText("");
        tSexo.setSelectedIndex(0);
        tApPaternoMod.setText("");
        tApMaternoMod.setText("");
        tNombreMod.setText("");
        tCompañiaMod.setText("");
        tDiaMod.setText("");
        tMesMod.setText("");
        tAnioMod.setText("");
        tNoClubPremierMod.setText("");
        tSexoMod.setSelectedIndex(0);
        
        id_cliente_actual = "";
    }
    
    private void listarID() {
        try {
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion connection = new Conexion();
            Connection con = connection.getConexion();
            
            String sql = "SELECT ID_Cliente FROM clientes";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
          
            int contador_aux = 0; 
            while(rs.next()) {
                
                    id_clientes[contador_aux] = Integer.parseInt(rs.getObject(1).toString());
                    contador_aux++;
            }
            
            con.close();
        } catch (SQLException e) {}
    }
    
    private void listarID(String where) {
        try {
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion connection = new Conexion();
            Connection con = connection.getConexion();
            
            String sql = "SELECT ID_Cliente FROM clientes" + where;
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
          
            int contador_aux = 0; 
            while(rs.next()) {
                
                    id_clientes[contador_aux] = Integer.parseInt(rs.getObject(1).toString());
                    contador_aux++;
            }
            
            con.close();
        } catch (SQLException e) {}
    }
    
    private boolean ComprobarApPaternoMod(){
        boolean existe;
        if(tApPaternoMod.getText().trim().equals("")) {
            existe = false;
        } else {
            existe = true;
        } 
        return existe;
    } 
    
    private boolean ComprobarNombreMod() {
        boolean existe;
        if(tNombreMod.getText().trim().equals("")) {
            existe = false;
        } else {
            existe = true;
        } 
        return existe;
    }
    
    private boolean RevisarFechaMod() {
        String fecha = tDiaMod.getText().trim() + "/" + tMesMod.getText().trim() + "/" + tAnioMod.getText().trim();
        if(tDiaMod.getText().trim().length()>0 && tMesMod.getText().trim().length()>0 && tAnioMod.getText().trim().length()>0) {
             try {
                SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
                formatoFecha.setLenient(false);
                formatoFecha.parse(fecha);
            } catch (ParseException e) {
                return false;
            }
             return true;
        } else {
            return true;
        }
    }
    
    private boolean RevisarDigitosFechaMod() {
        boolean esta_Bien;
        if(tDiaMod.getText().length()==2 && tMesMod.getText().length()==2 && tAnioMod.getText().length()==4) {
            esta_Bien = true;
        } else {
            esta_Bien = false;
        } 
        return esta_Bien;
    }
    
    private void editar(){
        if (!id_cliente_actual.equals("")) {
            
            boolean ap_Paterno_Existe = this.ComprobarApPaternoMod();
            boolean nombre_Existe = this.ComprobarNombreMod();
            boolean Digitos_Fecha_Bien = true;
            boolean Fecha_Bien = true;
            
            if (!(tDiaMod.getText().trim().equals("") && tMesMod.getText().trim().equals("") && tAnioMod.getText().trim().equals(""))) {
                Digitos_Fecha_Bien = this.RevisarDigitosFechaMod();
                Fecha_Bien = this.RevisarFechaMod(); 
            }
            
            if(ap_Paterno_Existe && nombre_Existe && Digitos_Fecha_Bien && Fecha_Bien){
                if((tDiaMod.getText().trim().equals("") && tMesMod.getText().trim().equals("") && tAnioMod.getText().trim().equals(""))
                || (tDiaMod.getText().trim().length()>0 && tMesMod.getText().trim().length()>0 && tAnioMod.getText().trim().length()>0)) {
                    Conexion connection = new Conexion();
                    Connection con = connection.getConexion();
                    PreparedStatement ps = null;
            
                    try {
                       
                        ps = con.prepareStatement("UPDATE clientes SET Apellido_Paterno=?, Apellido_Materno=?, Nombre=?, Compañia=?, Fecha_Nacimiento=?, Sexo=?, No_Club_Premier=? WHERE ID_Cliente = ?");
                        ps.setString(1, tApPaternoMod.getText());
                        ps.setString(2, tApMaternoMod.getText());
                        ps.setString(3, tNombreMod.getText());
                        ps.setString(4, tCompañiaMod.getText());
                
                        String fecha = tDiaMod.getText() + "/" + tMesMod.getText() + "/" + tAnioMod.getText();
                        if(tDiaMod.getText().trim().equals("") && tMesMod.getText().trim().equals("") && tAnioMod.getText().trim().equals("")) {
                            fecha = "";     
                        }
                        ps.setString(5, fecha);
                
                        ps.setString(6, tSexoMod.getSelectedItem().toString());
                        
                        String no_club_premier = tNoClubPremierMod.getText();
                        if(no_club_premier.equals("")) {
                            no_club_premier = "0";
                        }
                        ps.setString(7, no_club_premier);

                        ps.setInt(8, Integer.parseInt(id_cliente_actual));
                
                        int res = ps.executeUpdate();
                
                        if(res > 0) {
                            JOptionPane.showMessageDialog(null,"¡Datos del cliente actualizados!");
                        } else {
                            JOptionPane.showMessageDialog(null, "Ocurrio un error al actualizar los datos del cliente");
                        }
                
                        con.close();
                        actualizarTabla();
                        borrarDatosMod();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null,"Ocurrio un error al conectarse con la base de datos, favor de contactar al administrador del sistema para solucionar el problema","Operaciín fallida",JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Se detecto que en la fecha falta especificar un dato. Se debe especificar dia, mes y año en el siguiente formato: DD/MM/AAAA.","Operación fallida", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                if(!ap_Paterno_Existe) {
               JOptionPane.showMessageDialog(null, "El campo <Apellido Paterno> es obligatorio","Operación fallida", JOptionPane.WARNING_MESSAGE);
            }
            
            if(!nombre_Existe) {
               JOptionPane.showMessageDialog(null, "El campo <Nombre> es obligatorio","Operación fallida", JOptionPane.WARNING_MESSAGE); 
            }
            
            if(!Digitos_Fecha_Bien){
               JOptionPane.showMessageDialog(null, "El formato de la fecha no es correcto. El formato debe ser como sigue: DD/MM/AAAA (dos digitos para el dia, dos digitos para el mes, cuatro digitos para el año)","Operación fallida", JOptionPane.WARNING_MESSAGE);
            }
            
            if(!Fecha_Bien){
               JOptionPane.showMessageDialog(null, "La fecha no es correcta. Revise si: el dia no supere 30 o 31 dias dependiendo el mes, o bien 28 si es febrero y no es año bisiesto, o 29 si es año bisiesto; el mes debe estar entre 01 y 12; el año debe ser mayor a 0","Operación fallida", JOptionPane.WARNING_MESSAGE);
            }
            
            }  
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un registro de la tabla para poder actualizar los datos de un cliente");
        }
    }
    
    private void bEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditarActionPerformed
         this.editar();
    }//GEN-LAST:event_bEditarActionPerformed

    private void borrarDatosMod() {
        tCompañiaMod.setText("");
        tApPaternoMod.setText("");
        tApMaternoMod.setText("");
        tNombreMod.setText("");
        tDiaMod.setText("");
        tMesMod.setText("");
        tAnioMod.setText("");
        tNoClubPremier.setText("");
        tSexoMod.setSelectedIndex(0);
        tNoClubPremierMod.setText("");
        id_cliente_actual = "";
    }
    
    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        
        int pestaña_Seleccionada = jTabbedPane1.getSelectedIndex();
        if (pestaña_Seleccionada == 0) {
            bAgregar.setEnabled(true);
            bEditar.setEnabled(false);
            bBuscar.setEnabled(false);
            lAyudaClientes.setText("Consejo: ubique el cursor en los campos -Nombre-, -Año- o -No. Club Premier- y presione la tecla ENTER para agregar un cliente.");
        } else {
            bAgregar.setEnabled(false);
            bEditar.setEnabled(true);
            bBuscar.setEnabled(true);
            actualizarTabla();
            lAyudaClientes.setText("Consejo: deje el campo de búsqueda vacio, y haga clic en el boton de buscar (lupa) para volver a listar los registros.");
        }
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        borrarDatos();
        cantidad_id=0;
        String texto = tBuscar.getText();
        String campo = comboEntidadesClientes.getSelectedItem().toString();
        String where = "";
        
        if (campo.equals("Compañia")) {
            where = " WHERE Compañia LIKE '%" + texto + "%'";
        } else if (campo.equals("Apellido Paterno")) {
            where = " WHERE Apellido_Paterno LIKE '%" + texto + "%'";
        } else if (campo.equals("Apellido Materno")) {
            where = " WHERE Apellido_Materno LIKE '%" + texto + "%'";
        } else {
            where = " WHERE Nombre LIKE '%" + texto + "%'";
        } 
        
        if ("".equals(texto)) {
            where = "";
        }
        
        try {
            DefaultTableModel modelo = new CustomTableModel();
            jTClientes.setModel(modelo);
            
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion connection = new Conexion();
            Connection con = connection.getConexion();
            
            String sql = "SELECT Apellido_Paterno, Apellido_Materno, Nombre, Compañia, Fecha_Nacimiento, Sexo, No_Club_Premier FROM clientes" + where;
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();
            modelo.addColumn("Apellido Paterno");
            modelo.addColumn("Apellido Materno");
            modelo.addColumn("Nombre");
            modelo.addColumn("Compañia");
            modelo.addColumn("Fecha Nacimiento");
            modelo.addColumn("Sexo");
            modelo.addColumn("No. Club Premier");
            
            for (int i=0; i <= 6; i++) {
              jTClientes.getColumnModel().getColumn(i).setPreferredWidth(tamaño_Columnas);  
            }
            
            while(rs.next()) {
                Object[] filas = new Object[cantidadColumnas]; //ya que la tabla trabaja con objetos, metemos todo en objetos
                
                for (int i=0; i < cantidadColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                
                cantidad_id++;
                modelo.addRow(filas);
            }
            
            con.close();
            
        } catch (SQLException ex) {
            JOptionPane.showInputDialog("Error:" + ex);
        }
        
        id_clientes = new int[cantidad_id];
        
        this.listarID(where);
    }//GEN-LAST:event_bBuscarActionPerformed

    private void bBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarActionPerformed
        borrarDatos();
    }//GEN-LAST:event_bBorrarActionPerformed

    private void jTClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTClientesMouseClicked
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            Conexion connection = new Conexion();
            Connection con = connection.getConexion();

            int Fila = jTClientes.getSelectedRow();
            id_cliente_actual = id_clientes[Fila]+"";

            ps = con.prepareStatement("SELECT Apellido_Paterno, Apellido_Materno, Nombre, Compañia, Fecha_Nacimiento, Sexo, No_Club_Premier FROM clientes WHERE ID_Cliente = ?");
            ps.setInt(1, Integer.parseInt(id_clientes[Fila]+""));
            rs = ps.executeQuery();

            String[] fecha_parte;
            while (rs.next()) {
                tApPaternoMod.setText(rs.getString("Apellido_Paterno"));
                tApMaternoMod.setText(rs.getString("Apellido_Materno"));
                tNombreMod.setText(rs.getString("Nombre"));
                tCompañiaMod.setText(rs.getString("Compañia"));
                
                if(Integer.parseInt(rs.getString("No_Club_Premier")) != 0) {
                    tNoClubPremierMod.setText(rs.getString("No_Club_Premier"));
                } else {
                    tNoClubPremierMod.setText(""); 
                }
                
                if(!rs.getString("Fecha_Nacimiento").trim().equals("")) {
                   fecha_parte = rs.getString("Fecha_Nacimiento").split("/");
                    tDiaMod.setText(fecha_parte[0]);
                    tMesMod.setText(fecha_parte[1]);
                    tAnioMod.setText(fecha_parte[2]); 
                } else {
                    tDiaMod.setText("");
                    tMesMod.setText("");
                    tAnioMod.setText(""); 
                }
                tSexoMod.setSelectedItem(rs.getString("Sexo"));

            }
            con.close();
        } catch (SQLException ex) {
            JOptionPane.showInputDialog("Ocurrio un error: " + ex.toString());
        }
    }//GEN-LAST:event_jTClientesMouseClicked

    private void tDiaModFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tDiaModFocusGained
        labelDiaMod.setVisible(true);
        lAyudaClientes.setText("Modique aquí el dia de nacimiento del cliente, a dos dígitos.");
    }//GEN-LAST:event_tDiaModFocusGained

    private void tDiaModFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tDiaModFocusLost
        labelDiaMod.setVisible(false);
        lAyudaClientes.setText("");
    }//GEN-LAST:event_tDiaModFocusLost

    private void tMesModFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tMesModFocusGained
        labelMesMod.setVisible(true);
        lAyudaClientes.setText("Modifique aqui el mes de nacimiento del cliente, a dos dígitos.");
    }//GEN-LAST:event_tMesModFocusGained

    private void tMesModFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tMesModFocusLost
        labelMesMod.setVisible(false);
        lAyudaClientes.setText("");
    }//GEN-LAST:event_tMesModFocusLost

    private void tAnioModFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tAnioModFocusGained
        labelAñoMod.setVisible(true);
        lAyudaClientes.setText("Modifique aqui el año de nacimiento del cliente, a cuatro dígitos.");
    }//GEN-LAST:event_tAnioModFocusGained

    private void tAnioModFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tAnioModFocusLost
        labelAñoMod.setVisible(false);
        lAyudaClientes.setText("");
    }//GEN-LAST:event_tAnioModFocusLost

    private void tDiaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tDiaFocusGained
        labelDia.setVisible(true);
        lAyudaClientes.setText("Dia de nacimiento del cliente, a dos digitos");
    }//GEN-LAST:event_tDiaFocusGained

    private void tDiaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tDiaFocusLost
        labelDia.setVisible(false);
        lAyudaClientes.setText("");
    }//GEN-LAST:event_tDiaFocusLost

    private void tMesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tMesFocusGained
        labelMes.setVisible(true);
        lAyudaClientes.setText("Mes de nacimiento del cliente, a dos digitos");
    }//GEN-LAST:event_tMesFocusGained

    private void tMesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tMesFocusLost
        labelMes.setVisible(false);
        lAyudaClientes.setText("");
    }//GEN-LAST:event_tMesFocusLost

    private void tAnioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tAnioFocusGained
        labelAño.setVisible(true);
        lAyudaClientes.setText("Año de nacimiento del cliente, a cuatro dígitos");
    }//GEN-LAST:event_tAnioFocusGained

    private void tAnioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tAnioFocusLost
        labelAño.setVisible(false);
        lAyudaClientes.setText("");
    }//GEN-LAST:event_tAnioFocusLost

    private void tNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNombreKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.agregar();
        }
    }//GEN-LAST:event_tNombreKeyPressed

    private void tAnioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tAnioKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.agregar();
        }
    }//GEN-LAST:event_tAnioKeyPressed

    private void tNoClubPremierKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNoClubPremierKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.agregar();
        }
    }//GEN-LAST:event_tNoClubPremierKeyPressed

    private void bBorrarModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarModActionPerformed
        tCompañiaMod.setText("");
        tApPaternoMod.setText("");
        tApMaternoMod.setText("");
        tNombreMod.setText("");
        tDiaMod.setText("");
        tMesMod.setText("");
        tAnioMod.setText("");
        tSexoMod.setSelectedIndex(0);
        tNoClubPremierMod.setText("");
    }//GEN-LAST:event_bBorrarModActionPerformed

    private void tNombreModKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNombreModKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.editar();
        }
    }//GEN-LAST:event_tNombreModKeyPressed

    private void tAnioModKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tAnioModKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.editar();
        }
    }//GEN-LAST:event_tAnioModKeyPressed

    private void tNoClubPremierModKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNoClubPremierModKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.editar();
        }
    }//GEN-LAST:event_tNoClubPremierModKeyPressed

    private void tCompaniaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tCompaniaFocusGained
        lAyudaClientes.setText("Nombre de la empresa donde trabaja el cliente");
    }//GEN-LAST:event_tCompaniaFocusGained

    private void tCompaniaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tCompaniaFocusLost
        lAyudaClientes.setText("");
    }//GEN-LAST:event_tCompaniaFocusLost

    private void tApPaternoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tApPaternoFocusGained
        lAyudaClientes.setText("Apellido paterno del cliente");
    }//GEN-LAST:event_tApPaternoFocusGained

    private void tApPaternoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tApPaternoFocusLost
        lAyudaClientes.setText("");
    }//GEN-LAST:event_tApPaternoFocusLost

    private void tApMaternoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tApMaternoFocusGained
        lAyudaClientes.setText("Apellido materno del cliente");
    }//GEN-LAST:event_tApMaternoFocusGained

    private void tApMaternoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tApMaternoFocusLost
        lAyudaClientes.setText("");
    }//GEN-LAST:event_tApMaternoFocusLost

    private void tNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tNombreFocusGained
        lAyudaClientes.setText("Nombre o nombres del cliente");
    }//GEN-LAST:event_tNombreFocusGained

    private void tNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tNombreFocusLost
        lAyudaClientes.setText("");
    }//GEN-LAST:event_tNombreFocusLost

    private void tNoClubPremierFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tNoClubPremierFocusGained
        lAyudaClientes.setText("Si el cliente cuenta con un número de club premier, escríbalo");
    }//GEN-LAST:event_tNoClubPremierFocusGained

    private void tNoClubPremierFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tNoClubPremierFocusLost
        lAyudaClientes.setText("");
    }//GEN-LAST:event_tNoClubPremierFocusLost

    private void tBuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tBuscarFocusGained
        lAyudaClientes.setText("Escoga una categoría y escriba lo que desea buscar, después haga clic en el botón de buscar.");
    }//GEN-LAST:event_tBuscarFocusGained

    private void tBuscarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tBuscarFocusLost
        lAyudaClientes.setText("");
    }//GEN-LAST:event_tBuscarFocusLost

    private void tCompañiaModFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tCompañiaModFocusGained
        lAyudaClientes.setText("Modifique aquí la compañia del cliente.");
    }//GEN-LAST:event_tCompañiaModFocusGained

    private void tCompañiaModFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tCompañiaModFocusLost
        lAyudaClientes.setText("");
    }//GEN-LAST:event_tCompañiaModFocusLost

    private void tApPaternoModFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tApPaternoModFocusGained
        lAyudaClientes.setText("Modifique aquí el apellido paterno del cliente.");
    }//GEN-LAST:event_tApPaternoModFocusGained

    private void tApPaternoModFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tApPaternoModFocusLost
        lAyudaClientes.setText("");
    }//GEN-LAST:event_tApPaternoModFocusLost

    private void tApMaternoModFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tApMaternoModFocusGained
        lAyudaClientes.setText("Modifique aqui el apellido materno del cliente.");
    }//GEN-LAST:event_tApMaternoModFocusGained

    private void tApMaternoModFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tApMaternoModFocusLost
        lAyudaClientes.setText("");
    }//GEN-LAST:event_tApMaternoModFocusLost

    private void tNombreModFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tNombreModFocusGained
        lAyudaClientes.setText("Modifique aquí el nombre del cliente.");
    }//GEN-LAST:event_tNombreModFocusGained

    private void tNombreModFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tNombreModFocusLost
        lAyudaClientes.setText("");
    }//GEN-LAST:event_tNombreModFocusLost

    private void jTClientesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTClientesFocusGained
        lAyudaClientes.setText("Los datos se cargaron en el formulario con éxito. Cuando termine de modifcar, haga clic en el boton de modificar (lápiz).");
    }//GEN-LAST:event_jTClientesFocusGained

    private void jTClientesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTClientesFocusLost
        lAyudaClientes.setText("");
    }//GEN-LAST:event_jTClientesFocusLost

    private void jTClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTClientesMouseEntered
        lAyudaClientes.setText("Seleccione un registro de la tabla para cargar los datos en el formulario.");
    }//GEN-LAST:event_jTClientesMouseEntered

    private void jTClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTClientesMouseExited
        lAyudaClientes.setText("");
    }//GEN-LAST:event_jTClientesMouseExited

    private void bSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSalirMouseEntered
        lAyudaClientes.setText("Salir al menú principal");
    }//GEN-LAST:event_bSalirMouseEntered

    private void bAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAgregarMouseEntered
        if(bAgregar.isEnabled()) {
            lAyudaClientes.setText("Agregar cliente"); 
        } else {
            lAyudaClientes.setText("Boton deshabilitado en esta pestaña");
        }
    }//GEN-LAST:event_bAgregarMouseEntered

    private void bEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEditarMouseEntered
        if(bEditar.isEnabled()) {
            lAyudaClientes.setText("Editar datos del cliente"); 
        } else {
            lAyudaClientes.setText("Boton deshabilitado en esta pestaña");
        }
    }//GEN-LAST:event_bEditarMouseEntered

    private void bEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEditarMouseExited
        lAyudaClientes.setText("");
    }//GEN-LAST:event_bEditarMouseExited

    private void bBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bBuscarMouseEntered
        if(bBuscar.isEnabled()) {
            lAyudaClientes.setText("Buscar cliente"); 
        } else {
            lAyudaClientes.setText("Boton deshabilitado en esta pestaña");
        }
    }//GEN-LAST:event_bBuscarMouseEntered

    private void bBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bBuscarMouseExited
        lAyudaClientes.setText("");
    }//GEN-LAST:event_bBuscarMouseExited

    private void bAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAgregarMouseExited
        lAyudaClientes.setText("");
    }//GEN-LAST:event_bAgregarMouseExited

    private void bSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSalirMouseExited
        lAyudaClientes.setText("");
    }//GEN-LAST:event_bSalirMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Ayuda_Clientes ventana = new Ayuda_Clientes();
        ventana.setVisible(true);
        ventana.setLocationRelativeTo(null);
        ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mod_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mod_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mod_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mod_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mod_Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregar;
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bBorrarMod;
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bEditar;
    private javax.swing.JButton bSalir;
    private javax.swing.JComboBox<String> comboEntidadesClientes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTClientes;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lAyudaClientes;
    private javax.swing.JLabel labelAño;
    private javax.swing.JLabel labelAñoMod;
    private javax.swing.JLabel labelDia;
    private javax.swing.JLabel labelDiaMod;
    private javax.swing.JLabel labelMes;
    private javax.swing.JLabel labelMesMod;
    private javax.swing.JPanel pConsultas;
    private javax.swing.JPanel pRegistro;
    private javax.swing.JTextField tAnio;
    private javax.swing.JTextField tAnioMod;
    private javax.swing.JTextField tApMaterno;
    private javax.swing.JTextField tApMaternoMod;
    private javax.swing.JTextField tApPaterno;
    private javax.swing.JTextField tApPaternoMod;
    private javax.swing.JTextField tBuscar;
    private javax.swing.JTextField tCompania;
    private javax.swing.JTextField tCompañiaMod;
    private javax.swing.JTextField tDia;
    private javax.swing.JTextField tDiaMod;
    private javax.swing.JTextField tMes;
    private javax.swing.JTextField tMesMod;
    private javax.swing.JTextField tNoClubPremier;
    private javax.swing.JTextField tNoClubPremierMod;
    private javax.swing.JTextField tNombre;
    private javax.swing.JTextField tNombreMod;
    private javax.swing.JComboBox<String> tSexo;
    private javax.swing.JComboBox<String> tSexoMod;
    // End of variables declaration//GEN-END:variables
}

class CustomTableModel extends DefaultTableModel {
   @Override
   public boolean isCellEditable(int row, int column) {
      return false;
   }
}